apiVersion: v2
name: argocd-stack
description: ArgoCD setup for K3s cluster
type: application
version: 0.1.0

dependencies:
  - name: argo-cd
    version: 9.4.4
    repository: https://argoproj.github.io/argo-helm
